/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CarDriverRole;

import business.CongestionProblem.CongestionProblemDirectory;
import business.Location.Location;
import business.Enterprise.Enterprise;
import business.Location.LocationDirectory;
import business.Organization.CarDriverOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Swarup
 */
public class CarDriverWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private CarDriverOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private LocationDirectory locationDirectory;
    private CongestionProblemDirectory congestionProblemDirectory;
    /**
     * Creates new form CarDriverWorkAreaJPanel
     */
    public CarDriverWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CarDriverOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        locationDirectory=enterprise.getLocationDirectory();
        enterprise.addCongestionProblems();
        congestionProblemDirectory=enterprise.getCongestionProblemDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGPS = new javax.swing.JButton();
        btnCongestionProblem = new javax.swing.JButton();
        btnGetInformation = new javax.swing.JButton();
        btnWeatherForecast = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Car Driver Work Area:");

        btnGPS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGPS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Swarup\\Documents\\NetBeansProjects\\Working Project\\Actions-go-next-icon (1).png")); // NOI18N
        btnGPS.setText("GPS");
        btnGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPSActionPerformed(evt);
            }
        });

        btnCongestionProblem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCongestionProblem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Swarup\\Documents\\NetBeansProjects\\Working Project\\Actions-go-next-icon (1).png")); // NOI18N
        btnCongestionProblem.setText("Congestion Problem");
        btnCongestionProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongestionProblemActionPerformed(evt);
            }
        });

        btnGetInformation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGetInformation.setIcon(new javax.swing.ImageIcon("C:\\Users\\Swarup\\Documents\\NetBeansProjects\\Working Project\\Actions-go-next-icon (1).png")); // NOI18N
        btnGetInformation.setText("Get Information");
        btnGetInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetInformationActionPerformed(evt);
            }
        });

        btnWeatherForecast.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnWeatherForecast.setIcon(new javax.swing.ImageIcon("C:\\Users\\Swarup\\Documents\\NetBeansProjects\\Working Project\\Actions-go-next-icon (1).png")); // NOI18N
        btnWeatherForecast.setText("Weather Forecast");
        btnWeatherForecast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeatherForecastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnCongestionProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGetInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWeatherForecast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnGPS)
                .addGap(18, 18, 18)
                .addComponent(btnCongestionProblem)
                .addGap(18, 18, 18)
                .addComponent(btnGetInformation)
                .addGap(18, 18, 18)
                .addComponent(btnWeatherForecast)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPSActionPerformed
        GPSJPanel gPSJPanel = new GPSJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount);
        userProcessContainer.add("gPSJPanel", gPSJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGPSActionPerformed

    private void btnCongestionProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongestionProblemActionPerformed
        CongestionProblemJPanel congestionProblemJPanel = new CongestionProblemJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount, enterprise);
        userProcessContainer.add("congestionProblemJPanel", congestionProblemJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCongestionProblemActionPerformed

    private void btnGetInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetInformationActionPerformed
        GetInformationJPanel getInformationJPanel= new GetInformationJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount);
        userProcessContainer.add("getInformationJPanel", getInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGetInformationActionPerformed

    private void btnWeatherForecastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeatherForecastActionPerformed
        WeatherForecastJPanel weatherForecastJPanel= new WeatherForecastJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount);
        userProcessContainer.add("weatherForecastJPanel",weatherForecastJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWeatherForecastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCongestionProblem;
    private javax.swing.JButton btnGPS;
    private javax.swing.JButton btnGetInformation;
    private javax.swing.JButton btnWeatherForecast;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
